[2024-12-18T18:59:51.529+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T18:59:51.542+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.info_mssg manual__2024-12-18T13:29:37.308107+00:00 [queued]>
[2024-12-18T18:59:51.549+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.info_mssg manual__2024-12-18T13:29:37.308107+00:00 [queued]>
[2024-12-18T18:59:51.550+0530] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-18T18:59:51.572+0530] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): info_mssg> on 2024-12-18 13:29:37.308107+00:00
[2024-12-18T18:59:51.579+0530] {logging_mixin.py:190} WARNING - /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=64493) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-18T18:59:51.581+0530] {standard_task_runner.py:72} INFO - Started process 64520 to run task
[2024-12-18T18:59:51.582+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'info_mssg', 'manual__2024-12-18T13:29:37.308107+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/var/folders/h6/l2cjrfls77b6_h6zs5w5vn4r0000gn/T/tmpnxcfs22a']
[2024-12-18T18:59:51.587+0530] {standard_task_runner.py:105} INFO - Job 180: Subtask info_mssg
[2024-12-18T18:59:51.637+0530] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.info_mssg manual__2024-12-18T13:29:37.308107+00:00 [running]> on host Jayeshs-MacBook-Air.local
[2024-12-18T18:59:51.722+0530] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='info_mssg' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T13:29:37.308107+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-18T13:29:37.308107+00:00'
[2024-12-18T18:59:51.724+0530] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-18T18:59:51.724+0530] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-18T18:59:51.725+0530] {logging_mixin.py:190} INFO - Current task name:info_mssg state:running start_date:2024-12-18 13:29:51.542610+00:00
[2024-12-18T18:59:51.726+0530] {logging_mixin.py:190} INFO - Dag name:movie_pipeline and current dag run status:running
[2024-12-18T18:59:51.727+0530] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T18:59:51.735+0530] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/h6/l2cjrfls77b6_h6zs5w5vn4r0000gn/T
[2024-12-18T18:59:51.736+0530] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'page_extract start']
[2024-12-18T18:59:51.746+0530] {subprocess.py:99} INFO - Output:
[2024-12-18T18:59:51.759+0530] {subprocess.py:106} INFO - /bin/bash: page_extract: command not found
[2024-12-18T18:59:51.761+0530] {subprocess.py:110} INFO - Command exited with return code 127
[2024-12-18T18:59:51.775+0530] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-18T18:59:51.786+0530] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-18T18:59:51.787+0530] {logging_mixin.py:190} INFO - Task start:2024-12-18 13:29:51.542610+00:00 end:2024-12-18 13:29:51.785989+00:00 duration:0.243379
[2024-12-18T18:59:51.788+0530] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): info_mssg> dag:<DAG: movie_pipeline> dagrun:<DagRun movie_pipeline @ 2024-12-18 13:29:37.308107+00:00: manual__2024-12-18T13:29:37.308107+00:00, state:running, queued_at: 2024-12-18 13:29:37.336034+00:00. externally triggered: True>
[2024-12-18T18:59:51.790+0530] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2024-12-18T18:59:51.792+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movie_pipeline, task_id=info_mssg, run_id=manual__2024-12-18T13:29:37.308107+00:00, execution_date=20241218T132937, start_date=20241218T132951, end_date=20241218T132951
[2024-12-18T18:59:51.814+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T18:59:51.814+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 180 for task info_mssg (Bash command failed. The command returned a non-zero exit code 127.; 64520)
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-12-18T18:59:51.862+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-18T18:59:51.899+0530] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-18T18:59:51.908+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
