[2024-12-29T04:30:47.579+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-29T04:30:47.742+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.scrape_distributors scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2024-12-29T04:30:48.066+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.scrape_distributors scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2024-12-29T04:30:48.069+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 1
[2024-12-29T04:30:48.117+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_distributors> on 2024-12-28 00:00:00+00:00
[2024-12-29T04:30:48.129+0000] {standard_task_runner.py:72} INFO - Started process 197 to run task
[2024-12-29T04:30:48.143+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'scrape_distributors', 'scheduled__2024-12-28T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp6itr5xvv']
[2024-12-29T04:30:48.151+0000] {standard_task_runner.py:105} INFO - Job 113: Subtask scrape_distributors
[2024-12-29T04:30:48.369+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.scrape_distributors scheduled__2024-12-28T00:00:00+00:00 [running]> on host e0a3add0f1ca
[2024-12-29T04:30:49.211+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='scrape_distributors' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-28T00:00:00+00:00'
[2024-12-29T04:30:49.284+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-29T04:30:51.226+0000] {extract.py:319} INFO - Iteration: 0 and movie_id: tt13186482
[2024-12-29T04:31:25.047+0000] {extract.py:319} INFO - Iteration: 1 and movie_id: tt18259086
[2024-12-29T04:32:02.530+0000] {extract.py:319} INFO - Iteration: 2 and movie_id: tt5040012
[2024-12-29T04:32:17.154+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-29T04:32:17.314+0000] {process_utils.py:132} INFO - Sending 15 to group 197. PIDs of all processes in the group: [217, 223, 227, 228, 251, 253, 297, 260, 314, 425, 770, 295, 197]
[2024-12-29T04:32:17.345+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 197
[2024-12-29T04:32:17.366+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-29T04:32:17.364+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=260, status='terminated', started='04:30:49') (260) terminated with exit code None
[2024-12-29T04:32:17.413+0000] {connectionpool.py:827} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f05095b4370>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c2a5b6d446dcc6ca65c659978993b059/window
[2024-12-29T04:32:17.449+0000] {connectionpool.py:827} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f05095b4d30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c2a5b6d446dcc6ca65c659978993b059/window
[2024-12-29T04:32:17.533+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-29T04:32:17.519+0000] {connectionpool.py:827} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f05095b4eb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c2a5b6d446dcc6ca65c659978993b059/window
