[2024-12-26T15:16:52.709+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T15:16:53.056+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.parse_collection_page manual__2024-12-26T15:02:05.416978+00:00 [queued]>
[2024-12-26T15:16:53.096+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.parse_collection_page manual__2024-12-26T15:02:05.416978+00:00 [queued]>
[2024-12-26T15:16:53.116+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-26T15:16:53.312+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): parse_collection_page> on 2024-12-26 15:02:05.416978+00:00
[2024-12-26T15:16:53.332+0000] {standard_task_runner.py:72} INFO - Started process 1156 to run task
[2024-12-26T15:16:53.346+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'parse_collection_page', 'manual__2024-12-26T15:02:05.416978+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp66oowlsj']
[2024-12-26T15:16:53.363+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask parse_collection_page
[2024-12-26T15:16:54.478+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.parse_collection_page manual__2024-12-26T15:02:05.416978+00:00 [running]> on host 1712831d7ea4
[2024-12-26T15:16:55.191+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='parse_collection_page' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T15:02:05.416978+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T15:02:05.416978+00:00'
[2024-12-26T15:16:55.196+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T15:16:55.265+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/parse.py", line 94, in fact_parser
    with open(path,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'run_2024-12-26/collection_parsed_2024-12-26.json'
[2024-12-26T15:16:55.319+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movie_pipeline, task_id=parse_collection_page, run_id=manual__2024-12-26T15:02:05.416978+00:00, execution_date=20241226T150205, start_date=20241226T151653, end_date=20241226T151655
[2024-12-26T15:16:55.360+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T15:16:55.362+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 38 for task parse_collection_page ([Errno 2] No such file or directory: 'run_2024-12-26/collection_parsed_2024-12-26.json'; 1156)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/parse.py", line 94, in fact_parser
    with open(path,'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'run_2024-12-26/collection_parsed_2024-12-26.json'
[2024-12-26T15:16:55.394+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-26T15:16:55.483+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-26T15:16:55.492+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
