[2024-12-26T17:33:31.137+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T17:33:31.525+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.parse_movies manual__2024-12-26T17:07:20.299024+00:00 [queued]>
[2024-12-26T17:33:31.553+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.parse_movies manual__2024-12-26T17:07:20.299024+00:00 [queued]>
[2024-12-26T17:33:31.557+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-26T17:33:31.596+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): parse_movies> on 2024-12-26 17:07:20.299024+00:00
[2024-12-26T17:33:31.606+0000] {standard_task_runner.py:72} INFO - Started process 5077 to run task
[2024-12-26T17:33:31.614+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'parse_movies', 'manual__2024-12-26T17:07:20.299024+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpkxgxlkh8']
[2024-12-26T17:33:31.621+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask parse_movies
[2024-12-26T17:33:31.788+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.parse_movies manual__2024-12-26T17:07:20.299024+00:00 [running]> on host 1712831d7ea4
[2024-12-26T17:33:32.151+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='parse_movies' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T17:07:20.299024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T17:07:20.299024+00:00'
[2024-12-26T17:33:32.154+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T17:33:32.288+0000] {parse.py:109} INFO - Parsing movie_id: tt18259086
[2024-12-26T17:33:32.705+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/parse.py", line 167, in movie_parser
    movie_data_dict['release_date_id']=str(datetime.strptime(release_date,"%d-%b-%Y").date()).replace('-','')
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Dec 20, 2024' does not match format '%d-%b-%Y'
[2024-12-26T17:33:32.768+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movie_pipeline, task_id=parse_movies, run_id=manual__2024-12-26T17:07:20.299024+00:00, execution_date=20241226T170720, start_date=20241226T173331, end_date=20241226T173332
[2024-12-26T17:33:32.805+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T17:33:32.809+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 55 for task parse_movies (time data 'Dec 20, 2024' does not match format '%d-%b-%Y'; 5077)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/parse.py", line 167, in movie_parser
    movie_data_dict['release_date_id']=str(datetime.strptime(release_date,"%d-%b-%Y").date()).replace('-','')
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Dec 20, 2024' does not match format '%d-%b-%Y'
[2024-12-26T17:33:32.838+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-26T17:33:33.007+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-26T17:33:33.034+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
